### POST
POST http://localhost:8080/api/v1/nextPosition
Content-Type: application/json

{
        "start": {
            "lng": 126.9780,
            "lat": 37.5665
        },
        "angle": 90
      }
###
POST http://localhost:8080/api/v1/nextPosition
Content-Type: application/json

{
    "start": {
          "lat": 37.5665,
          "lng": 126.9780
    },
    "angle": 90
}

###
POST http://localhost:8080/api/v1/isInRegion
Content-Type: application/json

{
  "position": {
    "lng": 1.234,
    "lat": 1.222
  },
  "region": {
    "name": "central",
    "vertices": [
      {
        "lng": -3.192473,
        "lat": 55.946233
      },
      {
        "lng": -3.192473,
        "lat": 55.942617
      },
      {
        "lng": -3.184319,
        "lat": 55.942617
      },
      {
        "lng": -3.184319,
        "lat": 55.946233
      },
      {
        "lng": -3.192473,
        "lat": 55.946233
      }
    ]
  }
}

###
POST http://localhost:8080/api/v1/isInRegion
Content-Type: application/json

{
  "position": {
    "lng": 0,
    "lat": 0
  },
  "region": {
    "name": "test",
    "vertices": [
      {
        "lng": -1,
        "lat": -1
      },
      {
        "lng": -1,
        "lat": 1
      },
      {
        "lng": 1,
        "lat": 1
      },
      {
        "lng": 1,
        "lat": -1
      },
      {
        "lng": -1,
        "lat": -1
      }
    ]
  }
}

###
POST http://localhost:8080/api/v1/query
Content-type: application/json

[
  {
    "attribute": "capacity",
    "operator": "<",
    "value": "8"
  },
  {
    "attribute": "cooling",
    "operator": "=",
    "value": "true"
  }
]

### One medDispatchRec
POST http://localhost:8080/api/v1/queryAvailableDrones
Content-Type: application/json

[
    {
      "id": 0,
      "date": "2025-11-18",
      "time": "15:00",
      "requirements": {
          "capacity": 1.0,
          "cooling" : false
      }
    }
]

### Two medDispatchRec
POST http://localhost:8080/api/v1/queryAvailableDrones
Content-Type: application/json

[
  {
    "id": 0,
    "date": "2025-11-18",
    "time": "15:00",
    "requirements": {
      "capacity": 5.0
    },
    "delivery": {
      "lng": -3.1850728987662364,
      "lat": 55.944581901599435

    }
  },
  {
    "id": 1,
    "date": "2025-11-19",
    "time": "09:00",
    "requirements": {
      "capacity": 1.0,
      "maxCost": 50000
    },
    "delivery": {
      "lng": 3.1893256555401592,
      "lat": 55.94636100157118
    }
  }
]

### calcDeliveryPath
POST http://localhost:8080/api/v1/calcDeliveryPath
Content-Type: application/json

[
  {
    "id": 0,
    "date": "2025-11-18",
    "time": "15:00",
    "requirements": {
      "capacity": 5.0
    },
    "delivery": {
      "lng": -3.1867334497823663,
      "lat": 55.94432778784571

    }
  },
  {
    "id": 1,
    "date": "2025-11-19",
    "time": "09:00",
    "requirements": {
      "capacity": 1.0,
      "maxCost": 50000
    },
    "delivery": {
      "lng": -3.1902699046107728,
      "lat":  55.9519373497846
    }
  }
]
