### POST
POST http://localhost:8080/api/v1/nextPosition
Content-Type: application/json

{
        "start": {
            "lng": 126.9780,
            "lat": 37.5665
        },
        "angle": 90
      }
###
POST http://localhost:8080/api/v1/nextPosition
Content-Type: application/json

{
    "start": {
          "lat": 37.5665,
          "lng": 126.9780
    },
    "angle": 90
}

###
POST http://localhost:8080/api/v1/isInRegion
Content-Type: application/json

{
  "position": {
    "lng": 1.234,
    "lat": 1.222
  },
  "region": {
    "name": "central",
    "vertices": [
      {
        "lng": -3.192473,
        "lat": 55.946233
      },
      {
        "lng": -3.192473,
        "lat": 55.942617
      },
      {
        "lng": -3.184319,
        "lat": 55.942617
      },
      {
        "lng": -3.184319,
        "lat": 55.946233
      },
      {
        "lng": -3.192473,
        "lat": 55.946233
      }
    ]
  }
}

###
POST http://localhost:8080/api/v1/isInRegion
Content-Type: application/json

{
  "position": {
    "lng": 0,
    "lat": 0
  },
  "region": {
    "name": "test",
    "vertices": [
      {
        "lng": -1,
        "lat": -1
      },
      {
        "lng": -1,
        "lat": 1
      },
      {
        "lng": 1,
        "lat": 1
      },
      {
        "lng": 1,
        "lat": -1
      },
      {
        "lng": -1,
        "lat": -1
      }
    ]
  }
}

###
POST http://localhost:8080/api/v1/query
Content-type: application/json

[
  {
    "attribute": "costFinal",
    "operator": "=",
    "value": "3.5"
  },
  {
    "attribute": "maxMoves",
    "operator": "=",
    "value": "1500"
  }
]

### One medDispatchRec
POST http://localhost:8080/api/v1/calcDeliveryPathAsGeoJson
Content-Type: application/json

[ { "id": 1, "date": "2025-12-12", "time": "14:30:00", "requirements": { "capacity": 8.0, "cooling": true, "maxCost": 11.0 }, "delivery": { "lng": -3.1907237642840363, "lat": 55.94941687101488 } }, { "id": 2, "date": "2025-12-12", "time": "14:30:00", "requirements": { "capacity": 4.0 }, "delivery": { "lng": -3.1843055426973828, "lat": 55.94668429393913 } }, { "id": 3, "date": "2025-12-12", "time": "14:30:00", "requirements": { "capacity": 7.0, "cooling": true, "maxCost": 10.0 }, "delivery": { "lng": -3.189799207630236, "lat": 55.94279498507413 } }, { "id": 4, "date": "2025-12-12", "time": "14:20:00", "requirements": { "capacity": 6.0, "heating": true }, "delivery": { "lng": -3.1844710805008623, "lat": 55.94664821172111 } } ]


### Two medDispatchRec
POST http://localhost:8080/api/v1/queryAvailableDrones
Content-Type: application/json

[
  {
    "id": 0,
    "date": "2025-11-18",
    "time": "15:00",
    "requirements": {
      "capacity": 5.0
    },
    "delivery": {
      "lng": -3.1850728987662364,
      "lat": 55.944581901599435

    }
  },
  {
    "id": 1,
    "date": "2025-11-19",
    "time": "09:00",
    "requirements": {
      "capacity": 1.0,
      "maxCost": 50000
    },
    "delivery": {
      "lng": 3.1893256555401592,
      "lat": 55.94636100157118
    }
  }
]


### multi
POST http://localhost:8080/api/v1/calcDeliveryPath
Content-Type: application/json

[
  {
    "id": 201,
    "date": "2025-12-01",
    "time": "08:00:00",
    "delivery": { "lng": -3.1865, "lat": 55.9447 },
    "requirements": {
      "capacity": 5.0,
      "cooling": false,
      "heating": false,
      "maxCost": null
    }
  },
  {
    "id": 202,
    "date": "2025-12-01",
    "time": "19:00:00",
    "delivery": { "lng": -3.1870, "lat": 55.9450 },
    "requirements": {
      "capacity": 5.0,
      "cooling": false,
      "heating": false,
      "maxCost": null
    }
  }
]

### single
POST http://localhost:8080/api/v1/calcDeliveryPath
Content-Type: application/json

[
  {
    "id": 201,
    "delivery": { "lng": -3.2056, "lat": 55.9447 },
    "requirements": {
      "capacity": 6.0
  }}
]
